baseurl = "https://eigenbaukombinat.de"
DefaultContentLanguage = "de"
#DefaultContentLanguage = "ja"
title = "Eigenbau​kombinat"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
enableRobotsTXT = "true"

pagination.pagerSize = 5

[markup.goldmark.renderer]
unsafe= true

[Params]
  subtitle = "Makespace, Hackspace und Mitmachwerkstatt in Halle (Saale)"
  mainSections = ["about", "post","posts"]
  logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "2 January 2006"
  commit = false
  rss = true
  comments = false
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = false
  showRelatedPosts = true
  hideAuthor = false
  selfHosted = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[[Params.bigimg]]
  src = "img/slider-1.jpg"
  desc = "Keramik"
[[Params.bigimg]]
  src = "img/slider-2.jpg"
  desc = "Projekte"
[[Params.bigimg]]
  src = "img/slider-3.jpg"
  desc = "Hackspace"
[[Params.bigimg]]
  src = "img/slider-4.jpg"
  desc = "Projekte"
[[Params.bigimg]]
  src = "img/slider-5.jpg"
  desc = "Elektronik"
[[Params.bigimg]]
  src = "img/slider-6.jpg"
  desc = "Hardware"
[[Params.bigimg]]
  src = "img/slider-7.jpg"
  desc = "Handarbeit"
[[Params.bigimg]]
  src = "img/slider-8.jpg"
  desc = "Siebdruck"
[[Params.bigimg]]
  src = "img/slider-9.jpg"
  desc = "Metall"
[[Params.bigimg]]
  src = "img/slider-10.jpg"
  desc = "Holz"
[[Params.bigimg]]
  src = "img/slider-11.jpg"
  desc = "Garten"
[[Params.bigimg]]
  src = "img/slider-12.jpg"
  desc = "Streamingevents"

[languages]
  [languages.de]
    languageName = "Deutsch"
    weight = "1"
  [languages.en]
    languageName = "English"
    weight = "2"
    subtitle = "Makespace, Hackspace and workshop in Halle (Saale)"
[[languages.en.menu.main]]
    name = "post"
    url = "post/"
    weight = 1
    identifier = "blog"

[[languages.en.menu.main]]
    name = "post"
    url = "post/"
    weight = 1
    parent = "blog"

[[languages.en.menu.main]]
    name = "archiv"
    url = "archiv/"
    weight = 2
    parent = "blog"

[[languages.en.menu.main]]
    name = "category"
    url = "categories/"
    weight = 3
    parent = "blog"

[[languages.en.menu.main]]
    name = "tags"
    url = "tags/"
    weight = 4
    parent = "blog"

[[languages.en.menu.main]]
    name = "search"
    url = "en/page/search/"
    weight = 5
    parent = "blog"

[[languages.en.menu.main]]
    name = "events"
    url = "our-events/"
    weight = 2

[[languages.en.menu.main]]
    name = "about"
    weight = 3
    identifier = "uberuns"

[[languages.en.menu.main]]
    name = "about us"
    url = "about-us/"
    weight = 3
    parent = "uberuns"

[[languages.en.menu.main]]
    name = "Opening"
    url = "opening/"
    weight = 3
    parent = "uberuns"

[[languages.en.menu.main]]
    name = "workshop"
    url = "workshop/"
    weight = 4
    parent = "uberuns"
    
#[[languages.en.menu.main]]
#    name = "matrix"
#    url = "/unser-neuer-chat-und-nachrichtenserver/"
#    weight = 5
#    parent = "uberuns"

#[[languages.en.menu.main]]
#    name = "status"
#    url = "/extstatus/"
#    weight = 6
#    parent = "uberuns"

[[languages.en.menu.main]]
    name = "join us"
    url = "join-us/"
    weight = 7
    parent = "uberuns"

[[languages.en.menu.main]]
    name = "directions"
    url = "directions/"
    weight = 8
    parent = "uberuns"

[[languages.en.menu.main]]
    name = "Impressum"
    url = "impressum/"
    weight = 9
    parent = "uberuns"


#




[Author]
  name = "EBK Impressum"
  website = "https://eigenbaukombinat.de/impressum"
  email = "kontakt@eigenbaukombinat.de"
  facebook = "Eigenbaukombinat"
  github = "eigenbaukombinat"
#  gitlab = "username"
#  bitbucket = "username"
#  twitter = "ebkhalle"
#  reddit = "username"
#  linkedin = "username"
#  xing = "username"
#  stackoverflow = "users/XXXXXXX/username"
#  snapchat = "username"
  instagram = "ebkhalle"
  youtube = "channel/UCsfpJrx2csVoioxv6xrCqJA"
#  soundcloud = "username"
#  spotify = "username"
#  bandcamp = "username"
#  itchio = "username"
#  vk = "username"
#  paypal = "username"
  telegram = "ebk_halle"
#  500px = "username"
#  codepen = "username"
  mastodon = "chaos.social/@eigenbaukombinat"
#  kaggle = "username"
#  weibo = "username"
#  slack = "username"

[[menu.main]]
    name = "Blog"
    url = "post/"
    weight = 1
    identifier = "blog"

[[menu.main]]
    name = "Blog"
    url = "post/"
    weight = 1
    parent = "blog"

[[menu.main]]
    name = "Archiv"
    url = "archiv/"
    weight = 2
    parent = "blog"

[[menu.main]]
    name = "Kategorien"
    url = "categories/"
    weight = 3
    parent = "blog"

[[menu.main]]
    name = "Tags"
    url = "tags/"
    weight = 4
    parent = "blog"

[[menu.main]]
    name = "Suche"
    url = "search/"
    weight = 5
    parent = "blog"

[[menu.main]]
    name = "Veranstaltung"
    url = "/unsere-veranstaltungen/"
    weight = 2

[[menu.main]]
    name = "Über uns"
    weight = 3
    identifier = "uberuns"

[[menu.main]]
    name = "Über uns"
    url = "uber-uns/"
    weight = 3
    parent = "uberuns"
    
[[menu.main]]
    name = "Öffnungszeiten"
    url = "oeffnungszeiten/"
    weight = 3
    parent = "uberuns"

[[menu.main]]
    name = "Werkstatt"
    url = "/werkstatt/"
    weight = 4
    parent = "uberuns"
   
[[menu.main]]
    name = "Keramik Workshops"
    url = "/keramikworkshops/"
    weight = 1
    parent = "projekte"
    
[[menu.main]]
    name = "Jugendworkshops"
    url = "/jugendworkshops/"
    weight = 2
    parent = "projekte"
    
[[menu.main]]
    name = "Junghacker"
    url = "/junghacker/"
    weight = 3
    parent = "projekte"

[[menu.main]]
    name = "HaGeWe"
    url = "/hagewe/"
    weight = 4
    parent = "projekte"
    

[[menu.main]]
    name = "Matrix"
    url = "/unser-neuer-chat-und-nachrichtenserver/"
    weight = 5
    parent = "uberuns"

[[menu.main]]
    name = "status"
    url = "extstatus/"
    weight = 6
    parent = "uberuns"

[[menu.main]]
    name = "Mitmachen"
    url = "mitmachen/"
    weight = 7
    parent = "uberuns"

[[menu.main]]
    name = "Anfahrt"
    url = "anfahrt/"
    weight = 8
    parent = "uberuns"

[[menu.main]]
    name = "Impressum"
    url = "impressum/"
    weight = 9
    parent = "uberuns"

# Search index for lunr.js
[outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "search"

[outputs]
    home = ["HTML", "SearchIndex", "RSS"]
