name: Generate Hugo

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Install Hugo
        env:
          HUGO_VERSION: 0.148.2
        run: |
          mkdir ~/hugo
          cd ~/hugo
          curl -L "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz" --output hugo.tar.gz
          tar -xvzf hugo.tar.gz
          sudo mv hugo /usr/local/bin

      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          token: ${{ steps.app-token.outputs.token }}
          submodules: recursive

      - name: Fix detached head on public submodule
        run: |
          cd /home/runner/work/website-build/website-build/
          git checkout master
          cd /home/runner/work/website-build/website-build/public
          git checkout main

      - name: Hugo Build
        run: |
          cd /home/runner/work/website-build/website-build/
          hugo  --gc --minify

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          cd /home/runner/work/website-build/website-build/public

          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"

          git add -A .
          
          if git diff-index --quiet HEAD --; then
            echo "No changes..."
          else
            git commit -m "[CI] build hugo static site"
            git push -u origin main
          fi
